language: python
python:
- 2.7
- &latest_py3 3.6
# Check that all template lines from the skeleton project have been removed.
#   Do NOT remove this when customising your project.
before_install: ['! grep -R SKELETON | grep -v grep']
install:
- pip install -r requirements-dev.txt
- pip install coveralls tox tox-travis
script:
- tox
branches:
  except:
  - skeleton
jobs:
  include:
  - stage: build-docs
    python: *latest_py3
    install: pip install tox
    script: tox -e docs
  - stage: lint-check
    python: *latest_py3
    install: pip install tox
    script: skip
    after_script: tox -e lint
after_success:
- coveralls
cache: pip
before_script:
  # Disable IPv6. Ref travis-ci/travis-ci#8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
deploy:
  provider: pypi
  on:
    tags: true
  skip_existing: true
  user: amc6010
  password:
    secure: kbhhD67SMxOuPPXshgBRK4tvUt3TAK4pNhgpktrKLYA1mnj0CE0BITJATvGst2I4/JjzUlX5lhcsylPcep7jVdhRJquPofp6xbn0z1uHpKVanHQb6QWsBVBVteb1ovnT65Pg/TOV/cP3nvpXYch4r8kpTz4J8M5hDalqhIGdjk4QDKG1NQ2IFkSWWutRKmTynjyVUn4NzClp3ARgWvmAllyw0ev/abCA0j6LVAxHsPdwggG9E1Imo5HdvCJslQpZsEyoR2I3NBszOvfydcJl+pUn+fQDOk16clbO36lxSl085W6soaDp+HLwWvPPnG5WWit4IVp1wvlJu9+RN1LcimccPiU+zcDx84ljeF4nM/fdBZSarFCNf0N2+MdFb7ivz4Z54ZtAw7vXZnNQAqweJvoBTUMyXU9L4Vx+pJ3Kcx1hj26TQae+l5on/41HYUjhr6iYrL4kqeETmtPi2b8I0+L0cjQHxtJ/D7RQD8B1gzJhVmEYQOVBY03TMEhjVq0AGL1iEfVDW8t6QRW88lqDPldRtMaAq9bhuaiKxi94m3af7xyExnJJ2POP3SpkZb4arEImbdo+rEqjVdm7v2s4LFIJFVlZSeLtqL5/R4z5Vm9g7JqTBDlV59r0bJ/6Mq5L9dZTkQoFwC0EOyXiYW7lMSEV1eAaelBSBAwmqMkvgDw=

