language: python
python:
- 2.7
- 3.6
before_install:
- "! grep -R SKELETON | grep -v grep"
install:
- pip install -r requirements-dev.txt
- pip install coveralls pytest-cov
script:
- python setup.py checkdocs
- py.test --cov crookbook
- sphinx-build -W docs/ build/docs/
- pylint --disable=W crookbook.py
after_script:
- flake8
- pylint crookbook.py
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
  user: amc6010
  distributions: dists
  password:
    secure: kbhhD67SMxOuPPXshgBRK4tvUt3TAK4pNhgpktrKLYA1mnj0CE0BITJATvGst2I4/JjzUlX5lhcsylPcep7jVdhRJquPofp6xbn0z1uHpKVanHQb6QWsBVBVteb1ovnT65Pg/TOV/cP3nvpXYch4r8kpTz4J8M5hDalqhIGdjk4QDKG1NQ2IFkSWWutRKmTynjyVUn4NzClp3ARgWvmAllyw0ev/abCA0j6LVAxHsPdwggG9E1Imo5HdvCJslQpZsEyoR2I3NBszOvfydcJl+pUn+fQDOk16clbO36lxSl085W6soaDp+HLwWvPPnG5WWit4IVp1wvlJu9+RN1LcimccPiU+zcDx84ljeF4nM/fdBZSarFCNf0N2+MdFb7ivz4Z54ZtAw7vXZnNQAqweJvoBTUMyXU9L4Vx+pJ3Kcx1hj26TQae+l5on/41HYUjhr6iYrL4kqeETmtPi2b8I0+L0cjQHxtJ/D7RQD8B1gzJhVmEYQOVBY03TMEhjVq0AGL1iEfVDW8t6QRW88lqDPldRtMaAq9bhuaiKxi94m3af7xyExnJJ2POP3SpkZb4arEImbdo+rEqjVdm7v2s4LFIJFVlZSeLtqL5/R4z5Vm9g7JqTBDlV59r0bJ/6Mq5L9dZTkQoFwC0EOyXiYW7lMSEV1eAaelBSBAwmqMkvgDw=
after_success:
- coveralls
